---
name: Build App

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Compile the application
      run: |
        ./random_numbers/mvnw clean compile
    
    - name: Test the application
      run: |
        ./random_numbers/mvnw test
    
    - name: Build the application
      run: |
        ./random_numbers/mvnw package

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/random-numbers:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/random-numbers:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/random-numbers:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.repository_name }}:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.repository_name }}:latest

